# Generated by Django 5.1.4 on 2024-12-12 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_hall_image_hall_is_booked_alter_hall_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallBookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('event_name', models.CharField(max_length=100)),
                ('num_students', models.IntegerField()),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('faculty_coordinator_name', models.CharField(max_length=100)),
                ('faculty_coordinator_mobile', models.CharField(max_length=15)),
                ('student_coordinator_name', models.CharField(max_length=100)),
                ('student_coordinator_mobile', models.CharField(max_length=15)),
                ('event_description', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Canceled', 'Canceled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.hall')),
            ],
        ),
    ]
