# Generated by Django 5.1.4 on 2024-12-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_hallbookingrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('cancelled', 'Cancelled')], max_length=20)),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('report', models.FileField(blank=True, null=True, upload_to='reports/')),
            ],
        ),
    ]
