# Generated by Django 5.1.4 on 2024-12-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.AddField(
            model_name='hallbookingrequest',
            name='report_upload',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
